### ISSUE TITLE
Добавить всем пользователям ярлык на рабочий стол для быстрого доступа и лёгкое доменное имя

### ISSUE THREAD

**Issue by Alex-dyuk** [spaut33/LAS#13]

**Comment by AlexeyTcapaev** [comment]
Было решено сделать массовую рассылку с файлом-ярлыком,групповой политикой такое решить не представляется возможным

**Comment by Alex-dyuk** [comment]
Надо как-то это сделать, если никак, то собираемся все вместе, чтобы решить вопрос.

**Comment by AlexeyTcapaev** [comment]
на счёт доменного имени предлагаю перенести в перспективы,тк процесс этот не быстрый.если вообще уит позволит

**Comment by AlexeyTcapaev** [comment]
rdy
