### ISSUE TITLE
Добавить FAQ по основным вопросам

### ISSUE THREAD

**Issue by Alex-dyuk** [spaut33/LAS#14]
Текст запросить у @Alex-dyuk

**Comment by AlexeyTcapaev** [comment]
Была речь о списке с основными вопросами от юзверей,приложите сюда

**Comment by AlexeyTcapaev** [comment]
готово

**Comment by Alex-dyuk** [comment]
Уменьшить интервал в тексте

**Comment by AlexeyTcapaev** [comment]
готово

**Comment by Alex-dyuk** [comment]
сделать padding см. изображение
![image](https://user-images.githubusercontent.com/33317818/33198792-91b7efb0-d106-11e7-820d-76c73f0a5b99.png)

**Comment by Alex-dyuk** [comment]
уменьшить интервал в заголовках
![image](https://user-images.githubusercontent.com/33317818/33199136-6cf370d0-d108-11e7-82ac-a3575e5592bc.png)

**Comment by Alex-dyuk** [comment]
Сделать строки с новой строки в соответствии с документом
https://docs.google.com/document/d/1zSup4FEkNsVSsEJTwHJtFUwWGrzPiqejqiJ1Edme-wk/edit
![image](https://user-images.githubusercontent.com/33317818/33318990-3f71b436-d456-11e7-8160-05291d511b58.png)
