### ISSUE TITLE
Добавить кнопку выгрузку данных в excel для анализа 

### ISSUE THREAD

**Issue by Alex-dyuk** [spaut33/LAS#16]

**Comment by Alex-dyuk** [comment]
Очень срочно нужна кнопка выгрузки в excel, у пользователей с правом доступа на ввод объектов.

**Comment by AlexeyTcapaev** [comment]
для кнопки нужно обсудить с ромой текущий запрос представления

**Comment by AlexeyTcapaev** [comment]
сделана выгрузка за весь период

**Comment by Alex-dyuk** [comment]
@AlexeyTcapaev Где найти кнопку?
