### ISSUE TITLE
Сделать форму обратной связи

### ISSUE THREAD

**Issue by Alex-dyuk** [spaut33/LAS#17]
![image](https://user-images.githubusercontent.com/33317818/32326351-ef173962-bfeb-11e7-99fd-a03d00749ea5.png)

**Comment by AlexeyTcapaev** [comment]
ready

**Comment by Alex-dyuk** [comment]
Нужно сделать уведомление об отправке заявке, как на изображении и на почту
![image](https://user-images.githubusercontent.com/33317818/33267073-87326a38-d391-11e7-8ad0-4caf1980e663.png)

**Comment by Alex-dyuk** [comment]
Нужно, чтобы это же сообщение было отправлено на почту отправителю. см. предыдущий комментарий.
