### ISSUE TITLE
Кривое отображение в FF

### ISSUE THREAD

**Issue by spaut33** [spaut33/LAS#2]
![image](https://user-images.githubusercontent.com/5065694/32322781-cce0b860-bfd6-11e7-99f1-a886398548d9.png)

**Comment by spaut33** [comment]
#3

**Comment by spaut33** [comment]
FF 57.0 64 bit (последняя версия) баг подтверждается.

**Comment by AlexeyTcapaev** [comment]
![image](https://user-images.githubusercontent.com/25639891/32982195-7f88cdba-cc91-11e7-8cde-cf50bd4b6b3a.png)
