### ISSUE TITLE
Сделать функцию авторизации без пароля

### ISSUE THREAD

**Issue by Alex-dyuk** [spaut33/LAS#23]
Сейчас в случае неверного ввода пароля, появляется такая ошибка.
![image](https://user-images.githubusercontent.com/33317818/32714089-9c9f10b0-c865-11e7-96aa-f31dd1134f41.png)
Нужно сделать, чтобы выводилось просто сообщение о неправильно введённом пароле.

**Comment by spaut33** [comment]
@Alex-dyuk это связано с функцией авторизации без пароля

**Comment by spaut33** [comment]
в FF не работает? Возможно #3

**Comment by AlexeyTcapaev** [comment]
работает при обращении к серверу через IP

**Comment by Alex-dyuk** [comment]
Появляется всплывающее окно для ввода пароля
![image](https://user-images.githubusercontent.com/33317818/33005874-6c4f61c2-cde1-11e7-8c3a-b8425f648351.png)

**Comment by Alex-dyuk** [comment]
@Alex-dyuk А теперь нормально входит, буквально через 3 минуты повторно ввёл адрес, ничего не понимаю
