### ISSUE TITLE
Сортировка сотрудников

### ISSUE THREAD

**Issue by spaut33** [spaut33/LAS#33]
Сортировать сотрудников в алфавитном порядке для упрощения поиска.
![screenshot-85 143 134 93-40400-2017-11-17-22-39-35-590](https://user-images.githubusercontent.com/5065694/32965674-4bfc1686-cbe8-11e7-8441-917b3e4c1bd3.png)

**Comment by AlexeyTcapaev** [comment]
но ведь есть возможность ввода?

**Comment by spaut33** [comment]
@AlexeyTcapaev не нужно заставлять пользователя делать что-то по нашему сценарию, если есть альтернативный путь. зачем выпадающий список сделан?
