### ISSUE TITLE
Больше 8 часов

### ISSUE THREAD

**Issue by spaut33** [spaut33/LAS#34]
Заметил сегодня в промежуточной выгрузке, что у юзеров встречаются ошибки заполнения:\
Обычно рабочий день длится 8 часов, некоторые ставят 8 часов в двух разных объектах и у них получается 16 часов за день. Чаще всего это ошибка юзера и надо как-то ненавязчиво об этом предупреждать, показывать. Например, можно выделять цифры или фон ячеек цветом, если там заполнено более 8 часов или сумма больше 8 часов, но бывают переработки, поэтому надо показывать действительно ненавязчиво. :)

**Comment by AlexeyTcapaev** [comment]
я предлагаю решить это синхронизацией со скудом

**Comment by Alex-dyuk** [comment]
Предлагаю под итого выводить часы по скуду, если у сотрудника введено больше, чем по скуду, то итого подсвечивается красным + появляется уведомление прямо в системе. (Должна быть какая-то кнопка при нажатии на которую можно посмотреть уведомления).
