### ISSUE TITLE
Сортировка списков

### ISSUE THREAD

**Issue by spaut33** [spaut33/LAS#42]
Список проектов нужно сортировать по алфавиту:
![image](https://user-images.githubusercontent.com/5065694/37510681-05e8b866-290d-11e8-8231-fa762a9d5c6b.png)

**Comment by getman87** [comment]
Реализовать сортировку объектов по алфавиту, как при выборе новых проектов, так и при отображении уже заполненной у каждого конкретного сотрудника информации.
Реализовать возможность сортировки объектов мышью путем перетаскивания.

**Comment by spaut33** [comment]
> Реализовать возможность сортировки объектов мышью путем перетаскивания.
Лучше создать отдельный тикет для новой функции.

**Comment by spaut33** [comment]
#45
