### ISSUE TITLE
В иерархии проекта "концепции" сделать разбивку на отдельные объекты, а не на вид деятельности

### ISSUE THREAD

**Issue by getman87** [spaut33/LAS#49]
Данное изменение крайне требуется нашим экономистам для корректного выставления трудозатрат по концепциям в бухгалтерию АО "ГУОВ".
Сейчас мы можем оценить только общий объем всех отвлечений специалистов на концепции, но не видим шифры, на которые можно отнести данные затраты.

**Comment by spaut33** [comment]
Я думаю что это организационный вопрос, разработчик тут вряд ли чем-то может помочь. :)

**Comment by spaut33** [comment]
Объекты:

- анализ документации
- генеральный план
- здания и сооружения...
- наружные сети

нужно скрыть из списка выбора объектов и из отображения в таблице пользователей, но при этом оставить данные в бд
